# Generated by Django 4.0.4 on 2022-05-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación de la instancia.')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación de la instancia.')),
                ('user_id', models.IntegerField()),
                ('token', models.CharField(max_length=255)),
                ('expired_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
